### ISSUE TITLE
The value of mGPU->nnz has not been initialized

### ISSUE THREAD

**Issue by raul-torres-carvajal** [cguzman95/MultiGPUOpenMPCAMP#5]
https://github.com/cguzman95/MultiGPUOpenMPCAMP/blob/e867e87f789a4f11a1b281a7697108f3cca6456a/test.cu#L747

In my compiler is automatically set to zero

**Comment by raul-torres-carvajal** [comment]
It applies for mGPU->n_cells and mGPU->n_rows as well

**Comment by cguzman95** [comment]
Fixed in last commit.
